# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_From.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 865)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        self.main_widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.224, y1:0.705, x2:1, y2:0, stop:0 rgba(0, 192, 202, 243), stop:1 rgba(53, 53, 209, 240));\n"
"border-radius:40px;")
        self.main_widget.setObjectName("main_widget")
        self.Page_Widget = QtWidgets.QStackedWidget(self.main_widget)
        self.Page_Widget.setGeometry(QtCore.QRect(180, 40, 901, 681))
        self.Page_Widget.setStyleSheet("background-color:none;\n"
"boder-radius:20px;")
        self.Page_Widget.setObjectName("Page_Widget")
        self.page_one = QtWidgets.QWidget()
        self.page_one.setObjectName("page_one")
        self.BackGround_one = QtWidgets.QLabel(self.page_one)
        self.BackGround_one.setGeometry(QtCore.QRect(0, 0, 901, 651))
        self.BackGround_one.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.497, y1:0, x2:0.493, y2:1, stop:0 rgba(0, 0, 0, 76), stop:1 rgba(255, 255, 255, 63));")
        self.BackGround_one.setText("")
        self.BackGround_one.setObjectName("BackGround_one")
        self.label_2 = QtWidgets.QLabel(self.page_one)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 361, 151))
        self.label_2.setStyleSheet("font: 48pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.page_one)
        self.label_7.setGeometry(QtCore.QRect(410, 20, 361, 151))
        self.label_7.setStyleSheet("font: 48pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.Page_Widget.addWidget(self.page_one)
        self.page_two = QtWidgets.QWidget()
        self.page_two.setObjectName("page_two")
        self.BackGround_two = QtWidgets.QLabel(self.page_two)
        self.BackGround_two.setGeometry(QtCore.QRect(0, 0, 901, 651))
        self.BackGround_two.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.497, y1:0, x2:0.493, y2:1, stop:0 rgba(0, 0, 0, 76), stop:1 rgba(255, 255, 255, 63));")
        self.BackGround_two.setText("")
        self.BackGround_two.setObjectName("BackGround_two")
        self.label_3 = QtWidgets.QLabel(self.page_two)
        self.label_3.setGeometry(QtCore.QRect(50, 60, 361, 151))
        self.label_3.setStyleSheet("font: 48pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.page_two)
        self.label_8.setGeometry(QtCore.QRect(430, 60, 361, 151))
        self.label_8.setStyleSheet("font: 48pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.Page_Widget.addWidget(self.page_two)
        self.page_three = QtWidgets.QWidget()
        self.page_three.setObjectName("page_three")
        self.BackGround_three = QtWidgets.QLabel(self.page_three)
        self.BackGround_three.setGeometry(QtCore.QRect(0, 0, 901, 651))
        self.BackGround_three.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.497, y1:0, x2:0.493, y2:1, stop:0 rgba(0, 0, 0, 76), stop:1 rgba(255, 255, 255, 63));")
        self.BackGround_three.setText("")
        self.BackGround_three.setObjectName("BackGround_three")
        self.label_4 = QtWidgets.QLabel(self.page_three)
        self.label_4.setGeometry(QtCore.QRect(70, 70, 361, 151))
        self.label_4.setStyleSheet("font: 48pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.page_three)
        self.label_9.setGeometry(QtCore.QRect(430, 70, 361, 151))
        self.label_9.setStyleSheet("font: 48pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.Page_Widget.addWidget(self.page_three)
        self.page_setting = QtWidgets.QWidget()
        self.page_setting.setObjectName("page_setting")
        self.label = QtWidgets.QLabel(self.page_setting)
        self.label.setGeometry(QtCore.QRect(0, 0, 901, 651))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.497, y1:0, x2:0.493, y2:1, stop:0 rgba(0, 0, 0, 76), stop:1 rgba(255, 255, 255, 63));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.page_setting)
        self.label_5.setGeometry(QtCore.QRect(160, 150, 361, 151))
        self.label_5.setStyleSheet("font: 48pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_setting)
        self.label_6.setGeometry(QtCore.QRect(120, 340, 361, 151))
        self.label_6.setStyleSheet("font: 48pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.Page_Widget.addWidget(self.page_setting)
        self.label_Meau = QtWidgets.QLabel(self.main_widget)
        self.label_Meau.setGeometry(QtCore.QRect(10, 120, 161, 531))
        self.label_Meau.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.472, x2:1, y2:0.494, stop:0 rgba(0, 154, 162, 105), stop:1 rgba(58, 104, 184, 204));")
        self.label_Meau.setText("")
        self.label_Meau.setObjectName("label_Meau")
        self.Btn_exit = QtWidgets.QPushButton(self.main_widget)
        self.Btn_exit.setGeometry(QtCore.QRect(10, 570, 161, 81))
        self.Btn_exit.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 241, 255, 164), stop:1 rgba(76, 173, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"boder-radius:50px;}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(184, 251, 255, 164), stop:1 rgba(144, 201, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 154, 162, 164), stop:1 rgba(46, 104, 145, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"")
        self.Btn_exit.setObjectName("Btn_exit")
        self.Btn_meau = QtWidgets.QPushButton(self.main_widget)
        self.Btn_meau.setGeometry(QtCore.QRect(10, 120, 161, 81))
        self.Btn_meau.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 241, 255, 164), stop:1 rgba(76, 173, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"boder-radius:50px;}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(184, 251, 255, 164), stop:1 rgba(144, 201, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 154, 162, 164), stop:1 rgba(46, 104, 145, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"")
        self.Btn_meau.setObjectName("Btn_meau")
        self.Btn_PageOne = QtWidgets.QPushButton(self.main_widget)
        self.Btn_PageOne.setGeometry(QtCore.QRect(10, 210, 161, 81))
        self.Btn_PageOne.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 241, 255, 164), stop:1 rgba(76, 173, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"boder-radius:50px;}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(184, 251, 255, 164), stop:1 rgba(144, 201, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 154, 162, 164), stop:1 rgba(46, 104, 145, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"")
        self.Btn_PageOne.setObjectName("Btn_PageOne")
        self.Btn_PageTwo = QtWidgets.QPushButton(self.main_widget)
        self.Btn_PageTwo.setGeometry(QtCore.QRect(10, 300, 161, 81))
        self.Btn_PageTwo.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 241, 255, 164), stop:1 rgba(76, 173, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"boder-radius:50px;}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(184, 251, 255, 164), stop:1 rgba(144, 201, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 154, 162, 164), stop:1 rgba(46, 104, 145, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"")
        self.Btn_PageTwo.setObjectName("Btn_PageTwo")
        self.Btn_PageThree = QtWidgets.QPushButton(self.main_widget)
        self.Btn_PageThree.setGeometry(QtCore.QRect(10, 390, 161, 81))
        self.Btn_PageThree.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 241, 255, 164), stop:1 rgba(76, 173, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"boder-radius:50px;}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(184, 251, 255, 164), stop:1 rgba(144, 201, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 154, 162, 164), stop:1 rgba(46, 104, 145, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"")
        self.Btn_PageThree.setObjectName("Btn_PageThree")
        self.Btn_setting = QtWidgets.QPushButton(self.main_widget)
        self.Btn_setting.setGeometry(QtCore.QRect(10, 480, 161, 81))
        self.Btn_setting.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 241, 255, 164), stop:1 rgba(76, 173, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"boder-radius:50px;}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(184, 251, 255, 164), stop:1 rgba(144, 201, 243, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.587, y2:0, stop:0 rgba(0, 154, 162, 164), stop:1 rgba(46, 104, 145, 213));\n"
"font: 75 18pt \"Agency FB\";\n"
"}\n"
"")
        self.Btn_setting.setObjectName("Btn_setting")
        self.label_name = QtWidgets.QLabel(self.main_widget)
        self.label_name.setGeometry(QtCore.QRect(20, 710, 871, 101))
        self.label_name.setStyleSheet("background-color: none;\n"
"font: 26pt \"HGB4X_CNKI\";")
        self.label_name.setObjectName("label_name")
        self.label_QQ = QtWidgets.QLabel(self.main_widget)
        self.label_QQ.setGeometry(QtCore.QRect(10, 10, 81, 81))
        self.label_QQ.setStyleSheet("border-image: url(:/Img/IMG/QQ.jpg);")
        self.label_QQ.setText("")
        self.label_QQ.setObjectName("label_QQ")
        self.label_name_bakground = QtWidgets.QLabel(self.main_widget)
        self.label_name_bakground.setGeometry(QtCore.QRect(0, 730, 781, 81))
        self.label_name_bakground.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.551, x2:1, y2:0.551, stop:0 rgba(0, 0, 0, 76), stop:1 rgba(255, 255, 255, 63));\n"
"")
        self.label_name_bakground.setText("")
        self.label_name_bakground.setObjectName("label_name_bakground")
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Page_Widget.setCurrentIndex(2)
        self.Btn_meau.clicked.connect(MainWindow.Meau)
        self.Btn_PageOne.clicked.connect(MainWindow.ToPageOne)
        self.Btn_PageTwo.clicked.connect(MainWindow.ToPageTwo)
        self.Btn_PageThree.clicked.connect(MainWindow.ToPageThree)
        self.Btn_setting.clicked.connect(MainWindow.ToPageSetting)
        self.Btn_exit.clicked.connect(MainWindow.Exit)
        self.Btn_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "第一页"))
        self.label_7.setText(_translate("MainWindow", "第一页"))
        self.label_3.setText(_translate("MainWindow", "第二页"))
        self.label_8.setText(_translate("MainWindow", "第二页"))
        self.label_4.setText(_translate("MainWindow", "第三页"))
        self.label_9.setText(_translate("MainWindow", "第三页"))
        self.label_5.setText(_translate("MainWindow", "设置"))
        self.label_6.setText(_translate("MainWindow", "设置"))
        self.Btn_exit.setText(_translate("MainWindow", "Exit"))
        self.Btn_meau.setText(_translate("MainWindow", "Meau"))
        self.Btn_PageOne.setText(_translate("MainWindow", "PageOne"))
        self.Btn_PageTwo.setText(_translate("MainWindow", "PageTwo"))
        self.Btn_PageThree.setText(_translate("MainWindow", "PageThree"))
        self.Btn_setting.setText(_translate("MainWindow", "Setting"))
        self.label_name.setText(_translate("MainWindow", "Bilibili"))
import Resource_rc
